### ISSUE TITLE
[Query Pagination] Move all instances to a pattern

### ISSUE THREAD

**Issue by justintadlock** [x3p0-dev/x3p0-ideas#1]
The goal is to move any instance of the Query Pagination block to a pattern. This allows us to manage the pagination output from a single file. This is a very good thing for long-term maintenance (fewer potential bugs and no inconsistencies across usages). It would also make it more easily swappable with alternate pagination patterns on the templating side (swapping shouldn't be an issue in the editor).

Currently, pagination patterns are broken in WordPress. With the following fix, they can be included, but they do not use the correct `/page/*` links on inherited queries:

- https://github.com/WordPress/gutenberg/pull/58602

Related issues:

- https://github.com/WordPress/gutenberg/issues/38684
- https://github.com/WordPress/gutenberg/issues/48296

**Comment by carolinan** [comment]
This seems to have been fixed "somewhere in Gutenberg 18.x" if you don't mind testing it again.

**Comment by justintadlock** [comment]
@carolinan - This is still giving me the `?query-page=2` URLs on Gutenberg 18.3.

**Comment by codersantosh** [comment]
I'm still facing the same issue with the current Gutenberg version (19.3.0).

`<!-- wp:pattern {"slug":"theme-slug/pagination"} /-->`

Since many `core/query` block patterns are using the same pagination design, I’m temporarily resolving the issue in PHP by requiring pagination.php:

`require 'pagination.php';`
